### ISSUE TITLE
Доработать сущности для hibernate. Учесть, что появился Ломбок

### ISSUE THREAD

**Issue by BJCreslin** [BJCreslin/zHelper#15]
1. Сделать entity
2. Убрать сеттеры/гетеры. добавить Аннотации Ломбока 
3. Добавить Id
4. Конструкторы
5. Билдер

**Comment by BJCreslin** [comment]
Сущности из папки src\main\java\ru\zhelper\zhelper\models

**Comment by ggi-dev** [comment]
По идее там же сущность только одна Procurement, остальные это enum для этой сущности?
билдер можно создать аннотацией Lombok
