### ISSUE TITLE
Слой репозитория для объекта Procurement

### ISSUE THREAD

**Issue by BJCreslin** [BJCreslin/zHelper#41]
слой между JPA репозиторием и сервисом

**Comment by Sibiria78** [comment]
Pagination: https://www.baeldung.com/spring-data-jpa-pagination-sorting

**Comment by Sibiria78** [comment]
BJCreslin: "Нам еще нужны будут методы: 1) который получал бы коллекцию Procurement из базы по коллекции их id . Он нужен вот для чего: Пользователь запрашивает список закупок, на которые он подписался. Смысла нет отдавать ему список всех закупок из базы. Связь пользователь-закупка, хранятся в другой таблице. Мы вначале, соответственно получаем список id закупок, на которые подписан конкретный пользователь, а потом уже достаем их из базы.
2 ) Метод получения списка закупок с датой, которая раньше заданной. Этот метод пригодится для очищения базы от старых закупок.

Все методы, которые, возвращают коллекции, должны возвращать не просто коллекции, а объекты типа Pageable https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/domain/Pageable.html Что бы всю коллекцию не вываливать, а по странично."
