### ISSUE TITLE
Валидатор ссылок на закупки

### ISSUE THREAD

**Issue by BJCreslin** [BJCreslin/zHelper#5]
Сделать интерфейс и его имплементацию с одним методом.
Приходит String.
на выходе boolean. 
Метод проверяет. 
-----------------------

**Comment by Sibiria78** [comment]
Правильная ссылка выглядит например так?

https://zakupki.gov.ru/epz/orderplan/pg2020/general-info.html?plan-number=202103193002927004

**Comment by 1azyfox** [comment]
> Правильная ссылка выглядит например так?
> 
> https://zakupki.gov.ru/epz/orderplan/pg2020/general-info.html?plan-number=202103193002927004

Может выглядеть и так: 

https://zakupki.gov.ru/epz/order/notice/zk20/view/common-info.html?regNumber=0323300084121000065#

**Comment by BJCreslin** [comment]
Нет. Это неправильная ссылка.  Ссылка ведет на план- график возможного будущего размещения.
Вот например правильная ссылка на закупку по 44ФЗ
https://zakupki.gov.ru/epz/order/notice/ea44/view/common-info.html?regNumber=0322300077021000066
