### ISSUE TITLE
Внедрение Спринг Секюрити

### ISSUE THREAD

**Issue by BJCreslin** [BJCreslin/zHelper#51]
Реализовать авторизацию пользователя по логину и паролю;
Реализовать аутентификацию  по jwt токену;
Реализовать сервис и REST API авторизации и управлению пользователями в панели управления;
Реализовать аннотации, регулирующие доступ к узлам API;
Внедрить документацию REST API с помощью swagger.

**Comment by Sibiria78** [comment]
https://www.youtube.com/watch?v=Tke5zjCshkc
